<?php

namespace ContainerJCrVndi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_STtuG9GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.STtuG9G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.STtuG9G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Modules\\Dashboard\\DashboardController::index' => ['privates', '.service_locator.z0A7H.F.App\\Modules\\Dashboard\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Modules\\Reports\\PdfController::exportPdf' => ['privates', '.service_locator.z0A7H.F.App\\Modules\\Reports\\PdfController::exportPdf()', 'getPdfControllerexportPdfService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Modules\\Dashboard\\DashboardController:index' => ['privates', '.service_locator.z0A7H.F.App\\Modules\\Dashboard\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Modules\\Reports\\PdfController:exportPdf' => ['privates', '.service_locator.z0A7H.F.App\\Modules\\Reports\\PdfController::exportPdf()', 'getPdfControllerexportPdfService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Modules\\Dashboard\\DashboardController::index' => '?',
            'App\\Modules\\Reports\\PdfController::exportPdf' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Modules\\Dashboard\\DashboardController:index' => '?',
            'App\\Modules\\Reports\\PdfController:exportPdf' => '?',
        ]);
    }
}
