<?php

namespace ContainerJCrVndi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Modules\Reports\PdfController' shared autowired service.
     *
     * @return \App\Modules\Reports\PdfController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/Reports/PdfController.php';

        $container->services['App\\Modules\\Reports\\PdfController'] = $instance = new \App\Modules\Reports\PdfController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Modules\\Reports\\PdfController', $container));

        return $instance;
    }
}
