<?php

namespace ContainerJCrVndi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSurveyControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Modules\PublicUI\SurveyController' shared autowired service.
     *
     * @return \App\Modules\PublicUI\SurveyController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/PublicUI/SurveyController.php';

        $container->services['App\\Modules\\PublicUI\\SurveyController'] = $instance = new \App\Modules\PublicUI\SurveyController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Modules\\PublicUI\\SurveyController', $container));

        return $instance;
    }
}
