server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    # Tamaño máximo de subida (alineado con php.ini)
    client_max_body_size 50M;

    index index.php;

    location / {
        # Intenta servir archivo directo, si no existe redirige a index.php
        try_files $uri /index.php$is_args$args;
    }

    # Despachar peticiones PHP al contenedor app-php
    location ~ ^/index\.php(/|$) {
        fastcgi_pass app-php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        # Opcional: configurar variables requeridas por Symfony
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        
        # Evitar el re-uso de URIs que ya han sido resueltas
        internal;
    }

    # Retornar 404 para los demás archivos PHP
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}
