<?php

namespace ContainerKyuMbIW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComplianceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Modules\Compliance\ComplianceController' shared autowired service.
     *
     * @return \App\Modules\Compliance\ComplianceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/Compliance/ComplianceController.php';

        $container->services['App\\Modules\\Compliance\\ComplianceController'] = $instance = new \App\Modules\Compliance\ComplianceController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Modules\\Compliance\\ComplianceController', $container));

        return $instance;
    }
}
