<?php

namespace ContainerKyuMbIW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRiskControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Modules\Risks\RiskController' shared autowired service.
     *
     * @return \App\Modules\Risks\RiskController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Modules/Risks/RiskController.php';

        $container->services['App\\Modules\\Risks\\RiskController'] = $instance = new \App\Modules\Risks\RiskController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Modules\\Risks\\RiskController', $container));

        return $instance;
    }
}
