<?php

namespace Proxies\__CG__\App\Modules\Compliance;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ComplianceIndicator extends \App\Modules\Compliance\ComplianceIndicator implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'area' => [parent::class, 'area', null, 16],
        "\0".parent::class."\0".'criterion' => [parent::class, 'criterion', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isCritical' => [parent::class, 'isCritical', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'orderNumber' => [parent::class, 'orderNumber', null, 16],
        'area' => [parent::class, 'area', null, 16],
        'criterion' => [parent::class, 'criterion', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isCritical' => [parent::class, 'isCritical', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'orderNumber' => [parent::class, 'orderNumber', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
